# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.0
jobs:
  build:
    working_directory: ~/RichUtilsKt
    docker: 
      - image: circleci/android:api-30
    environment:
      JVM_OPTS: -Xmx3200m
    
    steps:
      - checkout
    
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run :
          name: display directory
          command: ls -la
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew build
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
          
      - run:
          name: Build debug APK and release APK
          command: |
            ./gradlew :app:build

      - run:
          name: "Pushing git tag"
          command: |
            git config user.email "amper2421@naver.com"
            git config user.name "JeonGu1Kang"
            git tag "${CIRCLE_BRANCH}4"
            git push -u origin circleci-project-setup --tags
            echo "Updated master tag with version test"
      
            
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/
          
    
