# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2
jobs:
  build:
    working_directory: ~/RichUtilsKt
    docker: 
      - image: circleci/android:api-30
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run :
          name: display directory
          command: ls -la
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew build
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
          
      - run:
          name: Build debug APK and release APK
          command: |
            ./gradlew :app:build
      - run:
          name: "Pushing git tag"
          command: |
                source ${BASH_ENV}
                    git config user.email "amper2421@naver.com"
                    git config user.name "JeonGuKang"
                    git tag -a ${NEW_TAG} -m "Updated master tag with version ${NEW_TAG}"
                    git push -u origin $NEW_TAG
                    echo "Updated master tag with version ${NEW_TAG}"
            
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/
          
      # - deploy:
      #     name: Trigger docs deployment
      #     command: |
      #       git config credential.helper 'cache --timeout=120'
      #       git config user.email "amper2421@naver.com"
      #       git config user.name "JeonGuKang"
      #       git commit --allow-empty -m "Trigger deployment"
      #       # Push quietly to prevent showing the token in log
      #       git push -q https://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@github.com/JeonGuKang/CircleCiTest.git master

    
