# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1
jobs:
  build:
    working_directory: ~/RichUtilsKt
    docker:
      - image: circleci/android@2.0.0
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run :
          name: display directory
          command: ls -la
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew build
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Build debug APK and release APK
          command: |
            ./gradlew :app:build
    
